import { Database } from "bun:sqlite";
import { hashPassword } from "better-auth/crypto";
import { USER_ROLE } from "@z3/types";
import { existsSync, readdirSync, writeFileSync } from "fs";
import { join, resolve } from "path";

const DEFAULT_PASSWORD = process.env.SEED_PASSWORD || "12345678";

export interface SeedUserConfig {
  id: string;
  name: string;
  email: string;
  role: USER_ROLE;
  password?: string;
}

export const SEED_USERS: SeedUserConfig[] = [
  {
    id: "usr_superadmin",
    name: "Super Admin",
    email: "superadmin@example.com",
    role: USER_ROLE.SUPER_ADMIN,
    password: DEFAULT_PASSWORD,
  },
  {
    id: "usr_admin",
    name: "Admin User",
    email: "admin@example.com",
    role: USER_ROLE.ADMIN,
    password: DEFAULT_PASSWORD,
  },
  {
    id: "usr_user",
    name: "Standard User",
    email: "user@example.com",
    role: USER_ROLE.USER,
    password: DEFAULT_PASSWORD,
  },
];

export async function seed() {
  console.log("🌱 Preparing seed data for users & credentials...");
  const now = Math.floor(Date.now() / 1000);
  const sqlStatements: string[] = [
    "-- Generated by apps/backend/src/db/seed.ts",
    "-- Run with: wrangler d1 execute sent-db --local --file=src/db/seed.sql",
    "",
  ];

  const preparedUsers = [];

  for (const u of SEED_USERS) {
    const password = u.password || DEFAULT_PASSWORD;
    const passwordHash = await hashPassword(password);
    const accountId = `acc_${u.role}`;

    preparedUsers.push({
      ...u,
      password,
      passwordHash,
      accountId,
    });

    sqlStatements.push(`-- ${u.name} (${u.role})`);
    sqlStatements.push(
      `INSERT INTO user (id, name, email, email_verified, role, banned, two_factor_enabled, created_at, updated_at) ` +
        `VALUES ('${u.id}', '${u.name}', '${u.email}', 1, '${u.role}', 0, 0, ${now}, ${now}) ` +
        `ON CONFLICT(email) DO UPDATE SET name=excluded.name, role=excluded.role, updated_at=excluded.updated_at;`
    );
    sqlStatements.push(
      `INSERT INTO account (id, user_id, account_id, provider_id, issuer, password, created_at, updated_at) ` +
        `VALUES ('${accountId}', '${u.id}', '${u.id}', 'credential', 'local:credential', '${passwordHash}', ${now}, ${now}) ` +
        `ON CONFLICT(id) DO UPDATE SET password=excluded.password, issuer=excluded.issuer, updated_at=excluded.updated_at;`
    );
    sqlStatements.push("");
  }

  // 1. Write SQL file
  const seedSqlPath = resolve(__dirname, "seed.sql");
  writeFileSync(seedSqlPath, sqlStatements.join("\n"), "utf8");
  console.log(`📄 Saved seed SQL file to: ${seedSqlPath}`);

  // 2. Direct local D1 SQLite seeding (if local state exists)
  const d1Dir = resolve(__dirname, "../../.wrangler/state/v3/d1/miniflare-D1DatabaseObject");
  let localDbSeeded = false;

  if (existsSync(d1Dir)) {
    const sqliteFiles = readdirSync(d1Dir).filter(
      (f) => f.endsWith(".sqlite") && f !== "metadata.sqlite"
    );

    for (const file of sqliteFiles) {
      const dbPath = join(d1Dir, file);
      try {
        const db = new Database(dbPath);

        // Check if user table exists
        const userTable = db
          .query("SELECT name FROM sqlite_master WHERE type='table' AND name='user'")
          .get();
        if (!userTable) continue;

        // Ensure issuer column exists on account table if created by an older schema
        const accountCols = db.query("PRAGMA table_info(account)").all() as Array<{ name: string }>;
        if (accountCols.length > 0 && !accountCols.some((c) => c.name === "issuer")) {
          db.run("ALTER TABLE account ADD COLUMN issuer text;");
        }

        const insertUser = db.prepare(`
          INSERT INTO user (id, name, email, email_verified, role, banned, two_factor_enabled, created_at, updated_at)
          VALUES (?, ?, ?, 1, ?, 0, 0, ?, ?)
          ON CONFLICT(email) DO UPDATE SET
            name=excluded.name,
            role=excluded.role,
            updated_at=excluded.updated_at
        `);

        const insertAccount = db.prepare(`
          INSERT INTO account (id, user_id, account_id, provider_id, issuer, password, created_at, updated_at)
          VALUES (?, ?, ?, 'credential', 'local:credential', ?, ?, ?)
          ON CONFLICT(id) DO UPDATE SET
            password=excluded.password,
            issuer=excluded.issuer,
            updated_at=excluded.updated_at
        `);

        for (const u of preparedUsers) {
          insertUser.run(u.id, u.name, u.email, u.role, now, now);
          insertAccount.run(u.accountId, u.id, u.id, u.passwordHash, now, now);
        }

        // Seed default Eurasie Travel pitch profile if pitch_profile table exists
        const pitchTable = db
          .query("SELECT name FROM sqlite_master WHERE type='table' AND name='pitch_profile'")
          .get();
        if (pitchTable) {
          const insertProfile = db.prepare(`
            INSERT INTO pitch_profile (user_id, name, target_url, value_proposition, tone_instructions, examples, created_at, updated_at)
            SELECT ?, ?, ?, ?, ?, ?, ?, ?
            WHERE NOT EXISTS (SELECT 1 FROM pitch_profile WHERE user_id = ? AND name = ?)
          `);
          const allUserIds = [...preparedUsers.map((u) => u.id), "dev-user-1"];
          for (const uid of allUserIds) {
            insertProfile.run(
              uid,
              "Eurasie Travel",
              "https://eurasietravel.com",
              "Inbound tour specialist and travel publisher covering Cambodia, Vietnam, Laos, Myanmar, and Thailand, specializing in private tailor-made itineraries and local experiential travel.",
              "Professional, collaborative, polite cold outreach requesting media kit and rate card",
              "Greeting Little Grey Box, ...",
              now,
              now,
              uid,
              "Eurasie Travel",
            );
          }
        }

        db.close();
        localDbSeeded = true;
        console.log(`💾 Applied seed data directly to local D1 SQLite: ${file}`);
      } catch (err) {
        console.warn(`⚠️ Could not seed local database at ${dbPath}:`, err);
      }
    }
  }

  console.log("\n✨ Seeding completed successfully!");
  console.log("------------------------------------------------------------");
  for (const u of preparedUsers) {
    console.log(
      `👤 ${u.name.padEnd(16)} | Email: ${u.email.padEnd(24)} | Role: ${u.role.padEnd(12)} | Password: ${u.password}`
    );
  }
  console.log("------------------------------------------------------------");
  if (!localDbSeeded) {
    console.log("ℹ️  To apply to remote or new D1: wrangler d1 execute sent-db --local --file=src/db/seed.sql");
  }
}

// Run when executed directly
if (import.meta.main) {
  seed().catch((err) => {
    console.error("❌ Seeding failed:", err);
    process.exit(1);
  });
}
