-- Generated by apps/backend/src/db/seed.ts
-- Run with: wrangler d1 execute sent-db --local --file=src/db/seed.sql

-- Super Admin (super_admin)
INSERT INTO user (id, name, email, email_verified, role, banned, two_factor_enabled, created_at, updated_at) VALUES ('usr_superadmin', 'Super Admin', 'superadmin@example.com', 1, 'super_admin', 0, 0, 1790406386, 1790406386) ON CONFLICT(email) DO UPDATE SET name=excluded.name, role=excluded.role, updated_at=excluded.updated_at;
INSERT INTO account (id, user_id, account_id, provider_id, issuer, password, created_at, updated_at) VALUES ('acc_super_admin', 'usr_superadmin', 'usr_superadmin', 'credential', 'local:credential', '06710021c063621afe857e61307b13f6:7c0382d8ff1413e760e5cc098f476d3e1376e709df87e7735375c9ac3fbff5f0b31b0a768f0a9ec98f970ad93f51f6bace61b7f6a0ed885331fe70119bfcbdca', 1790406386, 1790406386) ON CONFLICT(id) DO UPDATE SET password=excluded.password, issuer=excluded.issuer, updated_at=excluded.updated_at;

-- Admin User (admin)
INSERT INTO user (id, name, email, email_verified, role, banned, two_factor_enabled, created_at, updated_at) VALUES ('usr_admin', 'Admin User', 'admin@example.com', 1, 'admin', 0, 0, 1790406386, 1790406386) ON CONFLICT(email) DO UPDATE SET name=excluded.name, role=excluded.role, updated_at=excluded.updated_at;
INSERT INTO account (id, user_id, account_id, provider_id, issuer, password, created_at, updated_at) VALUES ('acc_admin', 'usr_admin', 'usr_admin', 'credential', 'local:credential', 'c3692e067ed4ef3bc704d22f88c3d587:88ee1988d4f2609ef00ecef4e46246ca542aee3e564dbdf9dd862024747d591b9eaf2d1eb70b33a91ad8cecbc1c5850b30520fd3710e0cc035a096f5a4bb5f0b', 1790406386, 1790406386) ON CONFLICT(id) DO UPDATE SET password=excluded.password, issuer=excluded.issuer, updated_at=excluded.updated_at;

-- Standard User (user)
INSERT INTO user (id, name, email, email_verified, role, banned, two_factor_enabled, created_at, updated_at) VALUES ('usr_user', 'Standard User', 'user@example.com', 1, 'user', 0, 0, 1790406386, 1790406386) ON CONFLICT(email) DO UPDATE SET name=excluded.name, role=excluded.role, updated_at=excluded.updated_at;
INSERT INTO account (id, user_id, account_id, provider_id, issuer, password, created_at, updated_at) VALUES ('acc_user', 'usr_user', 'usr_user', 'credential', 'local:credential', '99b68ec432ad80775c9803344a19a706:528cae7dca87d21234a119a5a53584527f24a02ca2af480d5b2969486a7aca36033f9bc815aecbc8690e6d9cecfd261d18b9a4dce6f989b5c443d76748373654', 1790406386, 1790406386) ON CONFLICT(id) DO UPDATE SET password=excluded.password, issuer=excluded.issuer, updated_at=excluded.updated_at;
