/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBacklinkResearchRouteImport } from './routes/_authenticated/backlink-research'
import { Route as AuthenticatedBulkSendRouteImport } from './routes/_authenticated/bulk-send'
import { Route as AuthenticatedCampaignQueueRouteImport } from './routes/_authenticated/campaign-queue'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedOutreachSettingsRouteImport } from './routes/_authenticated/outreach-settings'
import { Route as AuthenticatedSeoPartnersRouteImport } from './routes/_authenticated/seo-partners'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsMailRouteImport } from './routes/_authenticated/settings/mail'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacklinkResearchRoute =
  AuthenticatedBacklinkResearchRouteImport.update({
    id: '/backlink-research',
    path: '/backlink-research',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBulkSendRoute = AuthenticatedBulkSendRouteImport.update({
  id: '/bulk-send',
  path: '/bulk-send',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignQueueRoute =
  AuthenticatedCampaignQueueRouteImport.update({
    id: '/campaign-queue',
    path: '/campaign-queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutreachSettingsRoute =
  AuthenticatedOutreachSettingsRouteImport.update({
    id: '/outreach-settings',
    path: '/outreach-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeoPartnersRoute =
  AuthenticatedSeoPartnersRouteImport.update({
    id: '/seo-partners',
    path: '/seo-partners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMailRoute =
  AuthenticatedSettingsMailRouteImport.update({
    id: '/settings/mail',
    path: '/settings/mail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/backlink-research': typeof AuthenticatedBacklinkResearchRoute
  '/bulk-send': typeof AuthenticatedBulkSendRoute
  '/campaign-queue': typeof AuthenticatedCampaignQueueRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/outreach-settings': typeof AuthenticatedOutreachSettingsRoute
  '/seo-partners': typeof AuthenticatedSeoPartnersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/mail': typeof AuthenticatedSettingsMailRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/backlink-research': typeof AuthenticatedBacklinkResearchRoute
  '/bulk-send': typeof AuthenticatedBulkSendRoute
  '/campaign-queue': typeof AuthenticatedCampaignQueueRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/outreach-settings': typeof AuthenticatedOutreachSettingsRoute
  '/seo-partners': typeof AuthenticatedSeoPartnersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/mail': typeof AuthenticatedSettingsMailRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/backlink-research': typeof AuthenticatedBacklinkResearchRoute
  '/_authenticated/bulk-send': typeof AuthenticatedBulkSendRoute
  '/_authenticated/campaign-queue': typeof AuthenticatedCampaignQueueRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/outreach-settings': typeof AuthenticatedOutreachSettingsRoute
  '/_authenticated/seo-partners': typeof AuthenticatedSeoPartnersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/mail': typeof AuthenticatedSettingsMailRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backlink-research'
    | '/bulk-send'
    | '/campaign-queue'
    | '/emails'
    | '/forbidden'
    | '/outreach'
    | '/outreach-settings'
    | '/seo-partners'
    | '/users'
    | '/settings/account'
    | '/settings/mail'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/backlink-research'
    | '/bulk-send'
    | '/campaign-queue'
    | '/emails'
    | '/forbidden'
    | '/outreach'
    | '/outreach-settings'
    | '/seo-partners'
    | '/users'
    | '/'
    | '/settings/account'
    | '/settings/mail'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/backlink-research'
    | '/_authenticated/bulk-send'
    | '/_authenticated/campaign-queue'
    | '/_authenticated/emails'
    | '/_authenticated/forbidden'
    | '/_authenticated/outreach'
    | '/_authenticated/outreach-settings'
    | '/_authenticated/seo-partners'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/mail'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backlink-research': {
      id: '/_authenticated/backlink-research'
      path: '/backlink-research'
      fullPath: '/backlink-research'
      preLoaderRoute: typeof AuthenticatedBacklinkResearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulk-send': {
      id: '/_authenticated/bulk-send'
      path: '/bulk-send'
      fullPath: '/bulk-send'
      preLoaderRoute: typeof AuthenticatedBulkSendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign-queue': {
      id: '/_authenticated/campaign-queue'
      path: '/campaign-queue'
      fullPath: '/campaign-queue'
      preLoaderRoute: typeof AuthenticatedCampaignQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outreach-settings': {
      id: '/_authenticated/outreach-settings'
      path: '/outreach-settings'
      fullPath: '/outreach-settings'
      preLoaderRoute: typeof AuthenticatedOutreachSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seo-partners': {
      id: '/_authenticated/seo-partners'
      path: '/seo-partners'
      fullPath: '/seo-partners'
      preLoaderRoute: typeof AuthenticatedSeoPartnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mail': {
      id: '/_authenticated/settings/mail'
      path: '/settings/mail'
      fullPath: '/settings/mail'
      preLoaderRoute: typeof AuthenticatedSettingsMailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBacklinkResearchRoute: typeof AuthenticatedBacklinkResearchRoute
  AuthenticatedBulkSendRoute: typeof AuthenticatedBulkSendRoute
  AuthenticatedCampaignQueueRoute: typeof AuthenticatedCampaignQueueRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedOutreachSettingsRoute: typeof AuthenticatedOutreachSettingsRoute
  AuthenticatedSeoPartnersRoute: typeof AuthenticatedSeoPartnersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsMailRoute: typeof AuthenticatedSettingsMailRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBacklinkResearchRoute: AuthenticatedBacklinkResearchRoute,
  AuthenticatedBulkSendRoute: AuthenticatedBulkSendRoute,
  AuthenticatedCampaignQueueRoute: AuthenticatedCampaignQueueRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedOutreachSettingsRoute: AuthenticatedOutreachSettingsRoute,
  AuthenticatedSeoPartnersRoute: AuthenticatedSeoPartnersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsMailRoute: AuthenticatedSettingsMailRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
